include:
  - template: Auto-DevOps.gitlab-ci.yml

test:
  stage: test
  image: heroku/buildpacks:20
  script:
    - npm install
    - npm run test
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

lint:
  stage: test
  image: heroku/buildpacks:20
  script:
    - npm install
    - npm run lint:prod
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

e2e:
  stage: test
  image: heroku/buildpacks:20
  script:
    - npm install
    - npm run e2e:headless
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
