include:
  - template: Auto-DevOps.gitlab-ci.yml

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

variables:
  AUTO_DEVOPS_BUILD_IMAGE_CNB_ENABLED: "true"
  AUTO_DEVOPS_BUILD_IMAGE_CNB_BUILDER: "heroku/buildpacks:20"
  BUILDPACK_URL: "heroku/nodejs"

test:
  stage: test
  image: node:12.20.0-stretch
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm install
    - npm run test
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

lint:
  stage: test
  image: node:12.20.0-stretch
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm install
    - npm run lint:prod
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

e2e:
  stage: test
  image: node:12.20.0-stretch
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - npm install
    - npm run e2e:headless
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
