include:
  - template: Auto-DevOps.gitlab-ci.yml

test:
  stage: test
  image: gliderlabs/herokuish:latest
  script:
    - cp -R . /tmp/app
    - /bin/herokuish buildpack test
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

lint:
  stage: test
  image: gliderlabs/herokuish:latest
  script:
    - cp -$ . /tmp/app
    - npm run lint:prod

e2e:
  stage: test
  image: gliderlabs/herokuish:latest
  script:
    - cp -$ . /tmp/app
    - npm run e2e:headless
