name: CI

on:
    push:
      branches: master
    pull_request:
      branches: master
jobs:
# This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    steps:
    - name: See whether a corresponding branch exists
      run: |
        echo "${{ github.head_ref }}"
        if curl --head --silent --fail "https://github.com/UPchieve/web/tree/${{ github.head_ref }}" 2> /dev/null;
         then
          export HAS_SAME_SERVER_BRANCH=1
         else
          export HAS_SAME_SERVER_BRANCH=0
        fi
    # To save time, detach and pull some of the largest docker files
    # - run: (docker pull node:11 && docker pull mongo:4.2.3-bionic) &
    # - uses: actions/setup-node@v1
    #   with:
    #     node-version: '11.7.0'
    # # Create directories to put in web and server
    # - run: mkdir server
    # - run: mkdir web
    # # Checks-out tthe server repository under $GITHUB_WORKSPACE/server
    - run: export HAS_SAME_SERVER_BRANCH=0
    - name: Checkout a matching feature branch from server repo (if it exists)
      if: env.HAS_SAME_SERVER_BRANCH == 1
      uses: actions/checkout@v2
      with:
        repository: 'upchieve/server'
        path: 'server'
        ref: ${{ github.head_ref }}
    - name: Checkout a master branch from server repo (if there is no matching branch in server)
      if: env.HAS_SAME_SERVER_BRANCH == 0
      uses: actions/checkout@v2
      with:
        repository: 'upchieve/server'
        path: 'server'
    # # Checks-out this web repository under $GITHUB_WORKSPACE/web
    # - uses: actions/checkout@v2
    #   with:
    #     path: 'web'
    # # Create an empty directory to use for the volume, and start the container
    # - run: cd server && cp config.example.ts config.ts && mkdir mongo-volume && docker-compose up -d
    # - run: sleep 60
    # - run: cd web && npm install
    # - uses: cypress-io/github-action@v1
    #   with:
    #     working-directory: ./web
    #     browser: chrome
    #     start: npm run e2e